[package]
name = "async-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
libc = "0.2.161"
tokio = { version = "1.41.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "time",
] }
